### ISSUE TITLE
Adding an option to produce matches in a non-pretty way

### ISSUE THREAD

**Issue by a3nm** [remi-dupre/enum-spanner#2]
Currently the only way to produce the matches (short of counting them) is to display the complete string with the matches highlighted in color -- and of course doing this means that displaying each match is linear in the text. ;)

It would be better to have an option to produce each match only by indicating its endpoints

**Comment by remi-dupre** [comment]
The new parameter "-p" ("--no-print") should now do the trick!

**Comment by a3nm** [comment]
Any reason for '-p'? I'm thinking that '-n' would maybe be more logical,
by analogy with sed -n.

-- 
Antoine Amarilli
